baseURL = "/"
languageCode = "en"
title = "Personal Blog Starter"

disableKinds = []

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML"]

[sitemap]
changeFreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

enableRobotsTXT = true
